platform :ios, ‘8.0’

target ‘WebView’ do    

pod 'AFNetworking'

pod 'SVProgressHUD'

# 主模块(必须)
pod 'mob_sharesdk'
 
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'mob_sharesdk/ShareSDKUI'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 
# 使用配置文件分享模块（非必需）
pod 'mob_sharesdk/ShareSDKConfigFile'
 
# 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
pod 'mob_sharesdk/ShareSDKExtension'

pod 'JZLocationConverter'

end
